# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('expires', models.DateTimeField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
