# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='source',
            field=models.CharField(default='vk', max_length=100),
            preserve_default=False,
        ),
    ]
