# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_token_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=200)),
                ('group_id', models.PositiveIntegerField()),
            ],
        ),
    ]
